### ISSUE TITLE
It would be handy to make this `NODE_ENV` aware

### ISSUE THREAD

**Issue by prometheas** [coditorium/nodejs-read-config#3]
The thing I really like about this package is its ability to reference values from the env, as well as from the YAML document itself, and am eager to apply this capability to a few Express apps I'm working on. The apps, however, rely on the ability to config values that vary by named execution environment, as traditionally expressed in the Node world by the value of `NODE_ENV`.

Is this a capability that you'd consider suitable for inclusion in this package, given your vision? If so, I'm happy to have a go at it and throw a PR your way.

**Comment by pmendelski** [comment]
Sounds interesting. Although I am not sure I fully understand it. Could you give a sample configuration?

**Comment by prometheas** [comment]
Of course! Here's one that I've lifted from the [yaml-config project's README file](https://www.npmjs.com/package/yaml-config):

```yaml
default:
  redis:
    port: 6379                # redis server port 
    host: '127.0.0.1'         # redis host 
    password: ''              # to use with AUTH 
    db: 1                     # the test db 
    options: {}
test:
  redis:
    db: 12
production:
  redis:
    db: 0
  new_prop:
    hello: 'world'
```

It's a [relatively](https://www.npmjs.com/package/node-yaml-config) common [convention](https://www.npmjs.com/package/config-manager) that I'm keen to adopt, but the other guys are missing this lovely interpolation ability your library has :)
